### ISSUE TITLE
Future PRs

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core-review-club/website#14]
Please comment in this issue to request PRs to be covered in future review club meetings.

**Comment by ariard** [comment]
https://github.com/bitcoin/bitcoin/pull/16367 I think multiprocess build support need to be tested by a lot of people on different os/distros, would be cool if attendees try to build and see if instructions are straightforward enough

**Comment by mzumsande** [comment]
I would find https://github.com/bitcoin/bitcoin/pull/16702 interesting.

**Comment by michaelfolkson** [comment]
When should we make a decision by? Need to give time for people to read in advance. Any of the above would be good for me. Are the PRs in the table ones that are due to happen but just haven't been scheduled yet?

**Comment by MarcoFalke** [comment]
@jnewbery

**Comment by jnewbery** [comment]
@MarcoFalke  
> bitcoin/bitcoin#16698

Still a WIP. We can cover this when it's no longer WIP and is ready for code review

@mzumsande 
> I would find bitcoin/bitcoin#16702 interesting.

That PR is quite large (+559/-77) and requires a lot of contextual knowledge. I think it's a bit too ambitious for review club I'm afraid. (review club is mostly for new reviewers)

@MarcoFalke / @michaelfolkson 
> When should we make a decision by? Need to give time for people to read in advance. 

Ideally they'd be on the website with notes and questions one week in advance. That's always been my intention, but I haven't managed that the last couple of weeks. Any help organizing the review club would be greatly appreciated!

**Comment by jonatack** [comment]
https://github.com/bitcoin/bitcoin/pull/16851 Continue relaying transactions after they expire from mapRelay

https://github.com/bitcoin/bitcoin/pull/16400 Rewrite AcceptToMemoryPoolWorker using smaller parts

https://github.com/bitcoin/bitcoin/pull/16202/ Refactor network message deserialization

**Comment by jonatack** [comment]
It's been a couple of months since we did a @thebluematt PR. Say, https://github.com/bitcoin/bitcoin/pull/16825 "Default to 2 additional blocks-only connections over Tor", or any PR he would prefer.

**Comment by jonatack** [comment]
Possibly https://github.com/bitcoin/bitcoin/pull/15558 Don't query all DNS seeds at once (p2p). Despite only changing a few lines of code, the PR has a fair amount of discussion and a possible bug found post-merge.

**Comment by jonatack** [comment]
Proposed a twist on #15558 above in #38.

**Comment by jonatack** [comment]
Maybe one of the BIP174 PRs after that:

https://github.com/bitcoin/bitcoin/pull/17034 Bip174 extensions

https://github.com/bitcoin/bitcoin/pull/16463 [BIP 174] Implement serialization support for GLOBAL_XPUB field

**Comment by jonatack** [comment]
https://github.com/bitcoin/bitcoin/pull/16841 Replace GetScriptForWitness with GetScriptForDestination

https://github.com/bitcoin/bitcoin/pull/16910 wallet: reduce loading time by using unordered maps... data structures and flame graphs FTW :)

**Comment by jonatack** [comment]
https://github.com/bitcoin/bitcoin/pull/14430 Add more property based tests for basic bitcoin data structures

**Comment by jnewbery** [comment]
https://github.com/bitcoin/bitcoin/pull/15845 *wallet: Fast rescan with BIP157 block filters*. It's +375/-32, but the vast majority is in new test code. Changes to product code are only ~+50.

**Comment by jnewbery** [comment]
@ryanofsky suggests https://github.com/bitcoin/bitcoin/pull/16442/commits and says "PR is surprisingly not that complicated, and you could even limit review to the first 5 commits since the real functionality is all there (excluding tests, caching, tweaks)"

**Comment by michaelfolkson** [comment]
+1 for https://github.com/bitcoin/bitcoin/pull/14430 Add more property based tests for basic bitcoin data structures

Author of PR (Chris Stewart) answered my StackExchange question on property based tests here: https://bitcoin.stackexchange.com/questions/91780/property-based-tests-have-been-added-to-bitcoin-core-what-are-they-and-could-th

**Comment by jnewbery** [comment]
> bitcoin/bitcoin#17034 Bip174 extensions
> bitcoin/bitcoin#16463 [BIP 174] Implement serialization support for GLOBAL_XPUB field

One PSBT is enough. I've added 17034.

**Comment by jnewbery** [comment]
@jonatack 
> bitcoin/bitcoin#16841 Replace GetScriptForWitness with GetScriptForDestination

This looks like a simple refactor. I don't think there's much of substance to discuss here.

> bitcoin/bitcoin#16910 wallet: reduce loading time by using unordered maps... data structures and flame graphs FTW :)

This seems like a scary change for a 5% performance improvement (over something that usually takes a handful of seconds at startup). I'm not inclined to review this myself - is there a reason you think we should spend time on this?

**Comment by jnewbery** [comment]
I've put a check against all suggested PRs that I've added to the table above, or that we've covered in a previous review club, or that have been merged/closed for a while.

**Comment by Binh0103** [comment]
trùng lặp Bản sao của #

**Comment by jnewbery** [comment]
Just added bitcoin/bitcoin#17954 and bitcoin/bitcoin#16902

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/pull/18234 could be an interesting candidate

**Comment by jnewbery** [comment]
>  bitcoin/bitcoin#18234 could be an interesting candidate

I agree. Would you like to host?

**Comment by jonatack** [comment]
- [x] https://github.com/bitcoin/bitcoin/pull/18267 (new signet subset PR), @kallewoof can write notes, would need someone to host the regular meeting (I don't mind since I plan to review it anyway; if someone is keen that works too).

**Comment by ariard** [comment]
I would be glad to host BIP324 implementation : https://github.com/bitcoin/bitcoin/pull/18242, there is a lot of interesting context.

**Comment by jonatack** [comment]
> I would be glad to host BIP324 implementation : [bitcoin/bitcoin#18242](https://github.com/bitcoin/bitcoin/pull/18242), there is a lot of interesting context.

I agree, and it would be a good follow-up on https://bitcoincore.reviews/16202. Though that PR might be a bit on the large side for the review club.

**Comment by fjahr** [comment]
I would like to host https://github.com/bitcoin/bitcoin/pull/19105, ideally on 10th of June.

**Comment by jnewbery** [comment]
> I would be glad to host BIP324 implementation : bitcoin/bitcoin#18242, there is a lot of interesting context.

@ariard It'd be great to have you host a session on BIP324, but I agree with Jon that this PR is too large for PR review club. Is there some subset or prerequisite PR we could review instead. I think we should aim for a PR that's no more than 100 lines.

I'm happy for you to host on June 17th if you can find something suitable.

**Comment by ariard** [comment]
@jnewbery yes we can focus only on new serializer/deserializer and not cover the re-keying part. So from commit "Expose MAC length in chacha_poly_aead_h" to "Add BIP324 v2 transport serializer and deserializer".

This scope sounds reasonable ?

June 17th sounds great!

**Comment by sipa** [comment]
I'm happy to host one on https://github.com/bitcoin/bitcoin/pull/18468

**Comment by jnewbery** [comment]
> I would like to host bitcoin/bitcoin#19105, ideally on 10th of June.

@fjahr Yes please!

> we can focus only on new serializer/deserializer and not cover the re-keying part. So from commit "Expose MAC length in chacha_poly_aead_h" to "Add BIP324 v2 transport serializer and deserializer".

@ariard even that is ~400 lines, so it's a big ask for attendees to review. I think if we do host a meeting on that, we need to make sure we have really clear notes and that we publish them a bit earlier than normal to give people time to review.

Are you able to provide notes & questions by next Friday (June 5th)?

> I'm happy to host one on bitcoin/bitcoin#18468

@sipa That'd be amazing! We'll schedule it for June 24th.

**Comment by MarcoFalke** [comment]
![span png](https://user-images.githubusercontent.com/6399679/83296636-19afd280-a1bf-11ea-81ae-7d6593bebf76.jpg)


Sorry for the spam, feel free to hide as off topic.

**Comment by ariard** [comment]
@jnewbery Yes will send clear, concise, with-context, notes before Friday 12pm UTC :)

**Comment by jnewbery** [comment]
Thanks @ariard! Let me know if I can help with the notes in any way.

**Comment by fjahr** [comment]
I would like to do https://github.com/bitcoin/bitcoin/pull/19328 next. This is an early part of coinstatsindex but without the hashing algo so it can be merged without it. It has a good size and should be pretty accessible for beginners. There is a little overlap with #19055 but these parts in particular have undergone a lot of changes (partly based on feedback from the review club) and since the session on #19055 mostly discussed the hashing algo and the high level benefits of the whole project, I think going in depth into this part would still be worthwhile.

**Comment by pinheadmz** [comment]
I reviewed https://github.com/bitcoin/bitcoin/pull/18267/files (signet) and would be happy to host unless @jonatack or @kallewoof has dibs?
I'd like to send signet BTC to participants who get questions right :smile:  ...and compiled the branch :smile:

**Comment by jonatack** [comment]
@pinheadmz Yes, I proposed to run a signet session a few months back, because it's a nice tour of many different components of the codebase. Our worry was that it's quite a few LOC for a review club PR. IDK, maybe a particular interesting commit or subset of commits?

**Comment by kallewoof** [comment]
Would *love* to see a signet session, but @ajtowns is working on some cool changes, so my suggestion is to wait until that's done. :)

**Comment by jnewbery** [comment]
The whole signet PR is too much to cover in a review club meeting, but as @jonatack points out, we could cover a commit or subset of commits. I'd be happy for any of you to host that once aj's rework is ready for review.

**Comment by pinheadmz** [comment]
Would be a useful session just to explore the changes to `chainparams.cpp`? It would be a good review on what defines a network and signet in particular.

**Comment by jnewbery** [comment]
@pinheadmz - sounds good. Let's try to get it scheduled once aj has made his changes.

**Comment by michaelfolkson** [comment]
These suggestions for future ones look great. Can we add Taproot functional tests to this list that Greg S has agreed to host?

**Comment by michaelfolkson** [comment]
For broader topics (e.g. Signet, Core process separation, Core test framework) that could do with a longer session than a hour on a single PR and could be aided with visuals/screenshare we are looking for future topics for presentations and Socratic Seminars at London BitDevs (online). Please contact me if interested :)

**Comment by jnewbery** [comment]
I think it'd be good to do a session on the cryptography in https://github.com/bitcoin/bitcoin/pull/19055. We did a previous session on that PR when it contained a lot more, but it's been reduced to just the C++ implementation of MuHash and I think we could do a session focused on that.

**Comment by jonatack** [comment]
Yes. Another cryptography PR that's been on my review list since February is https://github.com/bitcoin/bitcoin/pull/18014.

**Comment by ryanofsky** [comment]
@jnewbery I'd like to do multiprocess https://github.com/bitcoin/bitcoin/pull/10102 and wallet transaction state https://github.com/bitcoin/bitcoin/pull/21206 review clubs at some point. Also if you're still looking for a host next week (saw mentioned in IRC) I could host for one of these or for a different PR

**Comment by MarcoFalke** [comment]
Nex week is taken ;) https://github.com/bitcoin-core-review-club/website/pull/420

**Comment by ryanofsky** [comment]
Just saw a missed message in IRC from @glozow, but I'd be happy to host a review club for https://github.com/bitcoin/bitcoin/pull/10102 anytime (since https://github.com/bitcoin/bitcoin/pull/21206 has already been merged).

**Comment by MarcoFalke** [comment]
I am unsure, but I think it is also allowed to host already merged prs for post-merge review clubs?

**Comment by jnewbery** [comment]
> I think it is also allowed to host already merged prs for post-merge review clubs?

Of course it is. Not only allowed, but encouraged.

**Comment by glozow** [comment]
@ryanofsky would you like to host on December 22nd? Either #21206 or #10102 would be great

**Comment by ryanofsky** [comment]
I'd do #10102 December 22. Will write up some notes and questions and open a PR to add them to the review club website, if that is the next step.

**Comment by glozow** [comment]
@ryanofsky great! Thank you 🤗

**Comment by jnewbery** [comment]
Closing. Please use the irc channel to request future PR review club meetings.
